name: 'ca_trademarks_dp'
version: '1.0.0'
config-version: 2

profile: 'ca_trademarks_dp'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ca_trademarks_dp:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +tags:
        - "stg"
        - "staging"
      cipo:
        base:
          +materialized: view
          +docs:
            node_color: '#7DB1B1' # Teal
          +tags:
            - "base"
    intermediate:
      +materialized: view
      +docs:
        node_color: '#F6BB42' # Sunflower
      +tags:
        - "int"
        - "intermediate"
    marts:
      +materialized: table
      +docs:
        node_color: '#4A89DC' # Blue Jeans
      +tags:
        - "marts"

seeds:
  ca_trademarks_dp:
    +docs:
      show: true
      node_color: '#A0D468' # Grass